### ISSUE TITLE
Problem loading recent diffuse models in fermipy 0.20.0

### ISSUE THREAD

**Issue by mpotto** [fermiPy/fermipy#364]
Hi, I'm having troubles when loading the V3 diffuse models from Pass 8 (P8R3_XXXX_V3). I was expecting that these models, being in my `refdata/fermi/galdiffuse` folder, could be normally loaded during setup, but the only IRFs available are prior to V3 and the same as listed by `gtirfs`. Is it normal? 

**Fermipy Installation**
I performed a brand-new `fermipy` installation using the `condainstall.sh` script as described in the docs. By using the default environment variables, running the script installed `fermipy` 0.17.4. Instead, I did:
```
curl -OL https://raw.githubusercontent.com/fermiPy/fermipy/master/condainstall.sh
export CONDA_PATH=<path to my conda installation> 
export INSTALL_CMD='pip install fermipy==0.20.0'
source condainstall.sh
```

**Problem Description**
I downloaded the 'mkn421' dataset used in the quickstart guide and changed the `config.yaml`to:

```yaml
data:
  ltcube : ltcube_239557414_428903014_z090_r180_gti.fits

binning:

  roiwidth   : 10.0
  binsz      : 0.1 
  binsperdec : 8   

selection:

  emin    : 100
  emax    : 316227.7660168379

  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin    : 239557414
  tmax    : 428903014 # 6 years
  filter  : null
  target  : mkn421

gtlike:

  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:

  src_radius  : null
  src_roiwidth : 15.0
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : ['4FGL']
``` 

Then, I did the following:
```python
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('config.yaml')
gta.setup()
```

and got the following error 

[error.txt](https://github.com/fermiPy/fermipy/files/5298871/error.txt)
